import './sass/main.scss';
import './js/slider';
import './js/contacts-modal';
import './js/about-modal';
import './js/mobile-menu';
import './js/modal-form';
import './js/scroll-up';
import './js/buy-now';
import './js/open-close';